### ISSUE TITLE
Updating the 'to do' list 

### ISSUE THREAD

**Issue by smkuhlani** [carob-data/carobiner#15]
Hallo Carobiners,

We have a [function](https://github.com/reagro/carobiner/blob/master/R/update_todo.R) on [Carobiner](https://github.com/reagro/carobiner/tree/master) for updating the 'to do' list to have an idea of which data sets have not been processed in Carob. The function however considers a 'processed data set' to be that in the compiled list only, not those in the _pending or _removed. Is this the correct way? or Can we consider those on the _pending or _removed list to be regarded processed as well?

**Comment by rhijmans** [comment]
"removed" is indeed equivalent to processed. I have remove the folder and added these files to the group where they belong as it is now possible to include files that do not write records; to avoid that they are processed again.

"pending" is not equivalent to processed. In fact, these scripts need priority attention. 

I have added a function `carobiner::on_github` that allows you to check if a file for a dataset exists on the repo and whether it is pending or not.
