### ISSUE TITLE
Empty cells seen as whitespaces

### ISSUE THREAD

**Issue by Soloibom** [carob-data/carobiner#19]
Empty cells are detected as whitespaces. Can it be replaced by NA by default?

**Comment by egbendito** [comment]
In my opinion is better if this is done in the carob script explicitly with something like `df[df == ""] <- NA`. It improves traceability, transparency and readibility of the standardization process, rather than hidding and obscuring things.

**Comment by Soloibom** [comment]
Also, I feel that the term 'whitespace' is not informative enough to point out the problem in the case of an empty cell.

**Comment by rhijmans** [comment]
`""` is not always best replaced with `NA`. Sometimes you have more information to know that it means zero, or "none".  Also note that you can get what you are after with e.g., `read.csv(na.strings=c("", "NA"))`
