### ISSUE TITLE
Quantitative Variable quality check

### ISSUE THREAD

**Issue by mukami3juma** [carob-data/carobiner#3]
quantitative_check is a function that seeks to ensure that the quantitative variables; biomass total and yield are numeric, that yield is above 0,that yield with NA entries is eliminated(assumption is NAs omitted should be less than 10%) and finally shows the distribution of the aforementioned variables, looking out for the mean, standard deviation, min, max in the summary statistics. This endeavor aims to determine if there are outliers and begs the question, where did the outliers come from?...is it from poor data entry or wrong units used.

```
quantitative_check <- function(d){
  library(dplyr)
  d <- d %>% filter(yield > 0)
  d <- d[,c("biomass_total","yield")]
  for(i in names(d)){
    summary(d[,i])
    NA_count <- sum(is.na(d[,i]))
    perc_NA <- (NA_count/nrow(d))*100
    mn <- mean(d[,i],na.rm = TRUE)
    std_dv <- sd(d[,i],na.rm = TRUE)
    # stats <- boxplot(d,main = "Data Distribution",xlab = "Variables of Interest",
    #                  ylab = "Values",col = "pink",border = "black")
    # get threshold values for outliers
    Tmin = mn-(3*std_dv)
    Tmax = mn+(3*std_dv)
    # find outliers
    outlier <- d[,i][which(d[,i] < Tmin | d[,i] > Tmax)]
    if(length(outlier) > 0){
      print(paste("Total outliers in",i,":",length(outlier)))
    }
    if(perc_NA > 10){
      print(paste("NAs above 10% threshold in",i))
    }
  }
}
```

**Comment by rhijmans** [comment]
Thanks, I have added a function `find_outliers` that you can use when writing your carob script. I have added automatic outlier checking for yield only (to get started).

**Comment by mukami3juma** [comment]
> Thanks, I have added a function `find_outliers` that you can use when writing your carob script. I have added automatic outlier checking for yield only (to get started).

Thank you.
