### ISSUE TITLE
Check range issue for crops depending variable

### ISSUE THREAD

**Issue by cedricngakou** [carob-data/carobiner#5]
I got  INVALID YIELD Error  when i was process a dataset containing Cassava Crop.  I notice that cassava crop yield in the whole dataset was out of range define for a crops yield.  Since  for some crop we can have a very widely value of yield , We proposed to perform the Check range by crop on the specific crops depending variable such as Yield, residue yield, Grain weight,  biomass, and  plant density. What do you thing about that?

I also  sent you an email with the proposed R code to go for that , please have a look and drop out your comment if applicable. Thank you

**Comment by egbendito** [comment]
Hello @cedricngakou this is a nice idea! Thanks!

I have tested the proposed `check_yield_range()` function you shared, but I am getting a strange output. This is the dummy data I am using:

```
check_yield_range(data.frame("crop" = c("cassava","cassava"), "yield" = c(11000,12000)),
                  read.csv("terms/records.csv"),
                  as.data.frame(readxl::read_excel("_todo/crop_test12.xlsx")))
```

But I get an `invalid: yield` message. I assume that's not the correct behaviour. Am I using it correctly?

**Comment by rhijmans** [comment]
Note that we want a standard measure for yield. For root and tuber crops this should probably be dry-weight.
The checks are general, and the upper bounds could be increased. We could also add an option to overwrite a boundary in a script, to deal with exceptional cases.

**Comment by egbendito** [comment]
I checked the updated function materials for the `check_ranges()` function you proposed @cedricngakou. The behaviour is as expected. 

My only suggestion would be to remove the `trms1` and `trms2` from the arguments, and keep them fixed within the function.

@rhijmans this is a more refined check for the upper and lower boundaries of crop-specific biophysical variables such as yield, biomass, grain_weight, etc. I feel is more appropriate that a generic check that can be switched off manually... Perhaps this feature can be tested on the cassava data referred above.

In anycase, if this is to be added, it would need to go into carobiner repo, not carob.

**Comment by rhijmans** [comment]
Implemented with https://github.com/reagro/carobiner/pull/7
